[[pages]]
path = "p/welcome.py"
name = "Home"

[[pages]]
path = "p/admin/user.py"
name = "Users"

[[pages]]
path = "p/admin/payment.py"
name = "Payments"

[[pages]]
path = "p/admin/communication.py"
name = "Communications"

[[pages]]
path = "p/admin/authorization.py"
name = "Authorizations"
