[[pages]]
path = "p/welcome.py"
name = "Início"

[[pages]]
path = "p/admin/user.py"
name = "Usuários"

[[pages]]
path = "p/admin/payment.py"
name = "Pagamentos"

[[pages]]
path = "p/admin/communication.py"
name = "Comunicações"

[[pages]]
path = "p/admin/authorization.py"
name = "Autorizações"
