[[pages]]
path = "p/welcome.py"
name = "Home"

[[pages]]
path = "p/parent/payment.py"
name = "Payments"

[[pages]]
path = "p/parent/communication.py"
name = "Communications"

[[pages]]
path = "p/parent/authorization.py"
name = "Authorizations"

[[pages]]
path = "p/parent/activity.py"
name = "Activities"
